receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # Permite conexões externas
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "otel-collector:4317"  # Ajustado para corresponder ao que a aplicação usa
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
